version: '3.8'

services:
  node-app:
    build: ./node_app
    ports:
      - "3005:3005"
    volumes:
      - ./node_app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3305:3305"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
