version: '3.8'

services:
  node-app:
    build: ./node_app
    ports:
      - "3000:3000"
    volumes:
      - ./node_app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
